#!/bin/env bash

for i in background heart splash; do
  ./imager.py ${i}.png --out=${i}.bin
  xxd -i $i.bin > $i.h
done

rm *.bin

cd font

for i in EX DOT QUES COMMA SPACE COLON {A..Z} {0..9}; do
  ../imager.py ${i}.png --out=${i}.bin
  xxd -i $i.bin > $i.h
done

rm *.bin
