#!/bin/sh

~/Desktop/imager.py EX.png --out=EX.bin
xxd -i EX.bin > EX.h 
~/Desktop/imager.py DOT.png --out=DOT.bin
xxd -i DOT.bin > DOT.h 
~/Desktop/imager.py QUES.png --out=QUES.bin 
xxd -i QUES.bin > QUES.h 
~/Desktop/imager.py COMMA.png --out=COMMA.bin
xxd -i COMMA.bin > COMMA.h 
~/Desktop/imager.py A.png --out=A.bin 
xxd -i A.bin > A.h 
~/Desktop/imager.py B.png --out=B.bin  
xxd -i B.bin > B.h 
~/Desktop/imager.py C.png --out=C.bin  
xxd -i C.bin > C.h 
~/Desktop/imager.py D.png --out=D.bin
xxd -i D.bin > D.h 
~/Desktop/imager.py E.png --out=E.bin  
xxd -i E.bin > E.h 
~/Desktop/imager.py F.png --out=F.bin 
xxd -i F.bin > F.h 
~/Desktop/imager.py G.png --out=G.bin  
xxd -i G.bin > G.h 
~/Desktop/imager.py H.png --out=H.bin  
xxd -i H.bin > H.h 
~/Desktop/imager.py I.png --out=I.bin  
xxd -i I.bin > I.h 
~/Desktop/imager.py J.png --out=J.bin  
xxd -i J.bin > J.h 
~/Desktop/imager.py K.png --out=K.bin  
xxd -i K.bin > K.h 
~/Desktop/imager.py L.png --out=L.bin  
xxd -i L.bin > L.h 
~/Desktop/imager.py M.png --out=M.bin  
xxd -i M.bin > M.h 
~/Desktop/imager.py N.png --out=N.bin  
xxd -i N.bin > N.h 
~/Desktop/imager.py O.png --out=O.bin  
xxd -i O.bin > O.h 
~/Desktop/imager.py P.png --out=P.bin  
xxd -i P.bin > P.h 
~/Desktop/imager.py Q.png --out=Q.bin  
xxd -i Q.bin > Q.h 
~/Desktop/imager.py R.png --out=R.bin  
xxd -i R.bin > R.h 
~/Desktop/imager.py S.png --out=S.bin  
xxd -i S.bin > S.h 
~/Desktop/imager.py T.png --out=T.bin  
xxd -i T.bin > T.h 
~/Desktop/imager.py U.png --out=U.bin  
xxd -i U.bin > U.h 
~/Desktop/imager.py V.png --out=V.bin  
xxd -i V.bin > V.h 
~/Desktop/imager.py W.png --out=W.bin  
xxd -i W.bin > W.h 
~/Desktop/imager.py X.png --out=X.bin  
xxd -i X.bin > X.h 
~/Desktop/imager.py Y.png --out=Y.bin  
xxd -i Y.bin > Y.h 
~/Desktop/imager.py Z.png --out=Z.bin  
xxd -i Z.bin > Z.h 
~/Desktop/imager.py 0.png --out=0.bin  
xxd -i 0.bin > 0.h 
~/Desktop/imager.py 1.png --out=1.bin  
xxd -i 1.bin > 1.h 
~/Desktop/imager.py 2.png --out=2.bin  
xxd -i 2.bin > 2.h 
~/Desktop/imager.py 3.png --out=3.bin  
xxd -i 3.bin > 3.h 
~/Desktop/imager.py 4.png --out=4.bin  
xxd -i 4.bin > 4.h 
~/Desktop/imager.py 5.png --out=5.bin  
xxd -i 5.bin > 5.h 
~/Desktop/imager.py 6.png --out=6.bin  
xxd -i 6.bin > 6.h 
~/Desktop/imager.py 7.png --out=7.bin  
xxd -i 7.bin > 7.h 
~/Desktop/imager.py 8.png --out=8.bin  
xxd -i 8.bin > 8.h 
~/Desktop/imager.py 9.png --out=9.bin  
xxd -i 9.bin > 9.h 

rm *.bin
